name: Upload to TestPyPI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
